### PR TITLE
node_memory_MemAvailable -> node_memory_MemFree; prometheus 1.1.1

### PR DESCRIPTION
**Pull request by ivankovnatsky**
prometheus 1.1.1. does not have "node_memory_MemAvailable" metric

__

Hi Carl, firstly thanks for the dashboard! I'm not sure which version or prometheus are you using, but with prometheus 1.1.1. memory gadget does not work.  I suspect they removed node_memory_MemAvailable in 1.1.1.

Ivan.

### CODE REVIEW

**Review by LuboVarga — CHANGES_REQUESTED** [review]
This fix is bad. It does not calculate percent of free memory, but percent of used memory. Add "100-" before whole.

**Comment by ivankovnatsky** [comment]
@LuboVarga, currenty query:

`(node_memory_MemFree{instance=~"$server"} / node_memory_MemTotal{instance=~"$server"}) * 100`

if you 100 - [the query above], you will get % of used memory.

**Comment by LuboVarga** [comment]
@sevenfourk Yep, you are right. I had different title for given stat in my local node exporter template. I will merge your pull request to mine.

**Comment by ivankovnatsky** [comment]
@LuboVarga yes, I've been customizing here too.  But I thought that this dashboard might better look original, like the author intended it to be.

**Comment by bergquist** [comment]
Thank you! 

Closing this since I merged #6

**Pull request closed without merging**
